
name: Ping Streamlit App

on:
  schedule:
    - cron: '*/10 * * * *'  # roda a cada 10 minutos (fuso horário UTC)
  workflow_dispatch:        # permite rodar manualmente também

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://plataforma-treinamento.streamlit.app/ > /dev/null
